services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: dennisoooo/news-frontend:v1  # 加上這行，指定映像名稱和標籤
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: dennisoooo/news-backend:v1    # 加上這行，指定映像名稱和標籤
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    command: python manage.py runserver 0.0.0.0:8001